language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/apt-cacher-ng
dist: trusty
services:
  - docker
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - USE_DOCKER=true
    - ROS_PARALLEL_JOBS="-j8 -l1"
    - CATKIN_PARALLEL_TEST_JOBS="-p1 -j8"
  matrix:
    - USE_TRAVIS=true ROS_DISTRO=hydro USE_DEB=true
    - USE_TRAVIS=true ROS_DISTRO=hydro USE_DEB=false NOT_TEST_INSTALL=true
    - USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=true
    - USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=false NOT_TEST_INSTALL=true
    - USE_TRAVIS=true ROS_DISTRO=kinetic USE_DEB=true
    - USE_TRAVIS=true ROS_DISTRO=kinetic USE_DEB=false NOT_TEST_INSTALL=true
    - USE_TRAVIS=true ROS_DISTRO=melodic USE_DEB=true
    - USE_TRAVIS=true ROS_DISTRO=melodic USE_DEB=false NOT_TEST_INSTALL=true BEFORE_SCRIPT="pwd; sed -i \"35iadd_definitions(-Wno-deprecated)\" hrpsys/CMakeLists.txt; (cd hrpsys; git diff)"
matrix:
  allow_failures:
    # if USE_DEB=false, testing time easily exceeds limits. Reduce the load on the host machine.
    - env: USE_TRAVIS=true ROS_DISTRO=hydro USE_DEB=false NOT_TEST_INSTALL=true
    - env: USE_TRAVIS=true ROS_DISTRO=indigo USE_DEB=false NOT_TEST_INSTALL=true
    - env: USE_TRAVIS=true ROS_DISTRO=kinetic USE_DEB=false NOT_TEST_INSTALL=true
    # hrpsys is not released completely on melodic
    - env: USE_TRAVIS=true ROS_DISTRO=melodic USE_DEB=true
before_install:
  # Install openrtm_aist & add osrf
  - add_scr="sudo apt-get install -qq -y ros-${ROS_DISTRO}-openrtm-aist; sudo -E sh -c \"echo \\\"deb http://packages.osrfoundation.org/gazebo/ubuntu-stable \`lsb_release -cs\` main\\\" > /etc/apt/sources.list.d/gazebo-latest.list\"; wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -; sudo apt-get update -qq"; if [ "${BEFORE_SCRIPT}" == "" ] ; then export BEFORE_SCRIPT=${add_scr}; else export BEFORE_SCRIPT="${BEFORE_SCRIPT}; ${add_scr}"; fi
  # Forcely upgrade PCRE to avoid failure in building hrpsys with hydro.
  # This has a side effect, and we need extra settings.
  # Issue detail: https://github.com/start-jsk/rtmros_common/issues/1076
  # .deb can be got from https://pkgs.org (e.g., https://pkgs.org/download/libpcre3)
  # libpcre3-dev requires the same version of libpcrecpp0
  - if [ "${ROS_DISTRO}" == "hydro" ] && [ "${USE_DEB}" != "true" ] ; then add_scr="wget archive.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre3_8.31-2ubuntu2_amd64.deb; wget archive.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcrecpp0_8.31-2ubuntu2_amd64.deb; wget archive.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre3-dev_8.31-2ubuntu2_amd64.deb; sudo dpkg -i libpcre3_8.31-2ubuntu2_amd64.deb; sudo dpkg -i libpcrecpp0_8.31-2ubuntu2_amd64.deb; sudo dpkg -i libpcre3-dev_8.31-2ubuntu2_amd64.deb; sudo apt-mark hold libpcre3 libpcrecpp0 libpcre3-dev"; if [ "${BEFORE_SCRIPT}" == "" ] ; then export BEFORE_SCRIPT=${add_scr}; else export BEFORE_SCRIPT="${BEFORE_SCRIPT}; ${add_scr}"; fi; fi
  # Forcely upgrading PCRE makes hrpsys_state_publisher dies:
  # https://github.com/start-jsk/rtmros_common/pull/1077#issuecomment-552102475
  # To avoid this, the following PRs are required:
  # https://github.com/ros/robot_model/pull/105, https://github.com/ros/robot_model/pull/106, https://github.com/ros/robot_model/pull/108
  # Also, see https://github.com/start-jsk/rtmros_common/pull/1077#issuecomment-552121026
  - if [ "${ROS_DISTRO}" == "hydro" ] && [ "${USE_DEB}" != "true" ] ; then export BEFORE_SCRIPT="${BEFORE_SCRIPT}; wstool set -y robot_model --git https://github.com/pazeshun/robot_model.git -v for-hydro-with-new-pcre; wstool update"; export ROSDEP_ADDITIONAL_OPTIONS="-n -q -r --ignore-src --skip-keys=liburdfdom-dev --skip-keys=liburdfdom-headers-dev"; fi
  # On kinetic and melodic, drcsim is not released
  - if [ ${ROS_DISTRO} != "kinetic" ] && [ ${ROS_DISTRO} != "melodic" ] ; then export BEFORE_SCRIPT="${BEFORE_SCRIPT}; sudo apt-get install -qq -y drcsim"; fi
  # Install libopencv-dev manually to compile hrpsys-simulator in hrpsys-base on kinetic
  # Details: https://github.com/start-jsk/rtmros_common/pull/1091#issuecomment-611457804
  #          https://github.com/start-jsk/rtmros_common/pull/1091#issuecomment-611476618
  # Waiting for .travis.rosinstall.kinetic to use hrpsys-release
  - if [ "${ROS_DISTRO}" == "kinetic" ] && [ "${USE_DEB}" != "true" ] ; then if [ "${EXTRA_DEB}" == "" ] ; then export EXTRA_DEB="libopencv-dev"; else export EXTRA_DEB="${EXTRA_DEB} libopencv-dev"; fi; fi
script:
  - if [ "${ROS_DISTRO}" == "hydro" ] ; then sudo apt-get install -y --force-yes gdebi && wget https://bintray.com/artifact/download/furushchev/ros-shadow-fixed/python-catkin-tools_0.3.1-1_all.deb && wget https://bintray.com/artifact/download/furushchev/ros-shadow-fixed/python-catkin-pkg_0.2.10-1_all.deb && sudo gdebi -n -q python-catkin-pkg_0.2.10-1_all.deb && sudo gdebi -n -q python-catkin-tools_0.3.1-1_all.deb && sudo apt-mark hold python-catkin-tools; fi
  - source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
